name: Test Cask

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  cask:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-15-intel, macos-26]
    runs-on: ${{ matrix.os }}
    permissions:
      actions: read
      contents: read
    steps:
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@1f8e202ffddf94def7f42f6fa3a482e821489f9c # 2026.07.10.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Cache Homebrew Bundler RubyGems
        uses: actions/cache@v5
        with:
          path: ${{ steps.set-up-homebrew.outputs.gems-path }}
          key: ${{ matrix.os }}-rubygems-${{ steps.set-up-homebrew.outputs.gems-hash }}
          restore-keys: ${{ matrix.os }}-rubygems-

      - run: brew test-bot --only-cleanup-before

      - run: brew test-bot --only-setup

      - run: brew test-bot --only-tap-syntax

      - run: brew style Casks/omnidock.rb

      - run: brew audit --cask --strict quanzhankeji/tap/omnidock

      - run: brew fetch --cask quanzhankeji/tap/omnidock
